using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace CrxMem.Core
{
    /// <summary>
    /// Generates beautiful, modern, responsive HTML reports for PE Analysis
    /// Includes all advanced features: Rich Header, MITRE ATT&CK, API Categories, etc.
    /// </summary>
    public static class HtmlExporter
    {
        public static string GeneratePEAnalysisReport(
            PEAnalyzer.PEInfo peInfo,
            AntiCheatDetector.DetectionResult acResult,
            string processName)
        {
            var html = new StringBuilder();

            // HTML Header with responsive CSS
            html.AppendLine("<!DOCTYPE html>");
            html.AppendLine("<html lang='en'>");
            html.AppendLine("<head>");
            html.AppendLine("    <meta charset='UTF-8'>");
            html.AppendLine("    <meta name='viewport' content='width=device-width, initial-scale=1.0'>");
            html.AppendLine($"    <title>PE Analysis Report - {processName}</title>");
            html.AppendLine("    <style>");
            html.AppendLine(GetCSS());
            html.AppendLine("    </style>");
            html.AppendLine("</head>");
            html.AppendLine("<body>");

            // Header
            html.AppendLine("    <div class='header'>");
            html.AppendLine("        <h1>🔍 PE Analysis Report</h1>");
            html.AppendLine($"        <h2>{EscapeHtml(processName)}</h2>");
            html.AppendLine($"        <p class='timestamp'>Generated: {DateTime.Now:yyyy-MM-dd HH:mm:ss}</p>");
            html.AppendLine("    </div>");

            html.AppendLine("    <div class='container'>");

            // Summary Section with Security Score
            html.AppendLine(GenerateSummarySection(peInfo, acResult));

            // API Categories Visualization
            if (peInfo.APICategories?.Count > 0)
            {
                html.AppendLine(GenerateAPICategories(peInfo));
            }

            // Security Score Dashboard
            html.AppendLine(GenerateSecurityScore(peInfo, acResult));

            // Tabbed Content - Now with 10 tabs!
            html.AppendLine("        <div class='tabs'>");
            html.AppendLine("            <button class='tab-btn active' onclick='openTab(event, \"imports\")'>📦 Imports</button>");
            html.AppendLine("            <button class='tab-btn' onclick='openTab(event, \"exports\")'>📤 Exports</button>");
            html.AppendLine("            <button class='tab-btn' onclick='openTab(event, \"delay\")'>⏱️ Delay Imports</button>");
            html.AppendLine("            <button class='tab-btn' onclick='openTab(event, \"sections\")'>📊 Sections</button>");
            html.AppendLine("            <button class='tab-btn' onclick='openTab(event, \"richheader\")'>🛠️ Rich Header</button>");
            html.AppendLine("            <button class='tab-btn' onclick='openTab(event, \"dependencies\")'>🔗 Dependencies</button>");
            html.AppendLine("            <button class='tab-btn' onclick='openTab(event, \"mitre\")'>🎯 MITRE ATT&CK</button>");
            html.AppendLine("            <button class='tab-btn' onclick='openTab(event, \"anticheat\")'>🛡️ Anti-Cheat</button>");
            html.AppendLine("            <button class='tab-btn' onclick='openTab(event, \"security\")'>🔒 Security</button>");
            html.AppendLine("            <button class='tab-btn' onclick='openTab(event, \"version\")'>ℹ️ Version Info</button>");
            html.AppendLine("        </div>");

            // Tab Content
            html.AppendLine(GenerateImportsTab(peInfo));
            html.AppendLine(GenerateExportsTab(peInfo));
            html.AppendLine(GenerateDelayImportsTab(peInfo));
            html.AppendLine(GenerateSectionsTab(peInfo));
            html.AppendLine(GenerateRichHeaderTab(peInfo));
            html.AppendLine(GenerateDependenciesTab(peInfo));
            html.AppendLine(GenerateMITRETab(peInfo));
            html.AppendLine(GenerateAntiCheatTab(acResult));
            html.AppendLine(GenerateSecurityTab(peInfo));
            html.AppendLine(GenerateVersionTab(peInfo));

            html.AppendLine("    </div>");

            // Back to top button
            html.AppendLine("    <button id='backToTop' class='back-to-top' onclick='scrollToTop()'>▲ Top</button>");

            // Footer
            html.AppendLine("    <div class='footer'>");
            html.AppendLine("        <p>🖥️ Generated by <strong>CrxMem PE Analyzer</strong> | For educational and research purposes</p>");
            html.AppendLine($"        <p class='small'>Report generated at {DateTime.Now:yyyy-MM-dd HH:mm:ss} | File: {EscapeHtml(peInfo.FilePath)}</p>");
            html.AppendLine("    </div>");

            // JavaScript
            html.AppendLine("    <script>");
            html.AppendLine(GetJavaScript());
            html.AppendLine("    </script>");

            html.AppendLine("</body>");
            html.AppendLine("</html>");

            return html.ToString();
        }

        private static string GenerateSummarySection(PEAnalyzer.PEInfo peInfo, AntiCheatDetector.DetectionResult acResult)
        {
            var sb = new StringBuilder();
            sb.AppendLine("        <div class='summary-grid'>");

            // Architecture Card
            sb.AppendLine("            <div class='card fadeIn'>");
            sb.AppendLine("                <div class='card-icon'>🖥️</div>");
            sb.AppendLine("                <div class='card-content'>");
            sb.AppendLine("                    <h3>Architecture</h3>");
            sb.AppendLine($"                    <p class='card-value'>{(peInfo.Is64Bit ? "x64 (64-bit)" : "x86 (32-bit)")}</p>");
            sb.AppendLine($"                    <p class='card-detail'>Entry: 0x{peInfo.EntryPoint:X}</p>");
            sb.AppendLine("                </div>");
            sb.AppendLine("            </div>");

            // Security Status Card
            int securityScore = 0;
            if (peInfo.HasASLR) securityScore += 25;
            if (peInfo.HasDEP) securityScore += 25;
            if (peInfo.HasCFG) securityScore += 25;
            if (peInfo.HasSEH) securityScore += 25;

            string securityClass = securityScore >= 75 ? "status-good" : (securityScore >= 50 ? "status-warning" : "status-danger");
            sb.AppendLine("            <div class='card fadeIn' style='animation-delay: 0.1s'>");
            sb.AppendLine("                <div class='card-icon'>🛡️</div>");
            sb.AppendLine("                <div class='card-content'>");
            sb.AppendLine("                    <h3>Security Features</h3>");
            sb.AppendLine($"                    <p class='card-value {securityClass}'>{securityScore}%</p>");
            sb.AppendLine($"                    <p class='card-detail'>ASLR:{(peInfo.HasASLR ? "✓" : "✗")} DEP:{(peInfo.HasDEP ? "✓" : "✗")} CFG:{(peInfo.HasCFG ? "✓" : "✗")} SEH:{(peInfo.HasSEH ? "✓" : "✗")}</p>");
            sb.AppendLine("                </div>");
            sb.AppendLine("            </div>");

            // Threat Level Card
            string threatClass = acResult.OverallThreat switch
            {
                "None" => "status-good",
                "Low" => "status-info",
                "Medium (User-Mode)" => "status-warning",
                _ => "status-danger"
            };
            sb.AppendLine("            <div class='card fadeIn' style='animation-delay: 0.2s'>");
            sb.AppendLine("                <div class='card-icon'>⚠️</div>");
            sb.AppendLine("                <div class='card-content'>");
            sb.AppendLine("                    <h3>Threat Level</h3>");
            sb.AppendLine($"                    <p class='card-value {threatClass}'>{acResult.OverallThreat}</p>");
            sb.AppendLine($"                    <p class='card-detail'>{acResult.DetectedAntiCheats.Count} Anti-Cheats</p>");
            sb.AppendLine("                </div>");
            sb.AppendLine("            </div>");

            // Compilation Date Card
            sb.AppendLine("            <div class='card fadeIn' style='animation-delay: 0.3s'>");
            sb.AppendLine("                <div class='card-icon'>📅</div>");
            sb.AppendLine("                <div class='card-content'>");
            sb.AppendLine("                    <h3>Compiled</h3>");
            sb.AppendLine($"                    <p class='card-value'>{peInfo.CompilationTime:yyyy-MM-dd}</p>");
            sb.AppendLine($"                    <p class='card-detail'>{peInfo.CompilationTime:HH:mm:ss} UTC</p>");
            sb.AppendLine("                </div>");
            sb.AppendLine("            </div>");

            // Compiler Info Card (Rich Header)
            if (!string.IsNullOrEmpty(peInfo.CompilerInfo))
            {
                sb.AppendLine("            <div class='card fadeIn' style='animation-delay: 0.4s'>");
                sb.AppendLine("                <div class='card-icon'>🛠️</div>");
                sb.AppendLine("                <div class='card-content'>");
                sb.AppendLine("                    <h3>Compiler</h3>");
                sb.AppendLine($"                    <p class='card-value-small'>{EscapeHtml(peInfo.CompilerInfo)}</p>");
                sb.AppendLine("                    <p class='card-detail'>From Rich Header</p>");
                sb.AppendLine("                </div>");
                sb.AppendLine("            </div>");
            }

            // Import Hash Card
            if (!string.IsNullOrEmpty(peInfo.ImpHash) && peInfo.ImpHash != "N/A")
            {
                sb.AppendLine("            <div class='card fadeIn' style='animation-delay: 0.5s'>");
                sb.AppendLine("                <div class='card-icon'>🔑</div>");
                sb.AppendLine("                <div class='card-content'>");
                sb.AppendLine("                    <h3>ImpHash</h3>");
                sb.AppendLine($"                    <p class='card-value-small monospace'>{peInfo.ImpHash.Substring(0, Math.Min(16, peInfo.ImpHash.Length))}...</p>");
                sb.AppendLine($"                    <button class='copy-btn' onclick='copyToClipboard(\"{peInfo.ImpHash}\")'>Copy Full Hash</button>");
                sb.AppendLine("                </div>");
                sb.AppendLine("            </div>");
            }

            sb.AppendLine("        </div>");
            return sb.ToString();
        }

        private static string GenerateAPICategories(PEAnalyzer.PEInfo peInfo)
        {
            var sb = new StringBuilder();
            sb.AppendLine("        <div class='section-card'>");
            sb.AppendLine("            <h2>📊 API Usage by Category</h2>");
            sb.AppendLine("            <div class='api-categories'>");

            int maxCount = peInfo.APICategories.Values.Max();
            foreach (var cat in peInfo.APICategories.OrderByDescending(c => c.Value))
            {
                int percentage = maxCount > 0 ? (cat.Value * 100 / maxCount) : 0;
                string barClass = GetCategoryClass(cat.Key);

                sb.AppendLine("                <div class='api-category-item'>");
                sb.AppendLine($"                    <div class='api-category-label'>{EscapeHtml(cat.Key)}<span class='api-count'>{cat.Value}</span></div>");
                sb.AppendLine($"                    <div class='api-category-bar'>");
                sb.AppendLine($"                        <div class='api-category-fill {barClass}' style='width: {percentage}%'></div>");
                sb.AppendLine("                    </div>");
                sb.AppendLine("                </div>");
            }

            sb.AppendLine("            </div>");
            sb.AppendLine("        </div>");
            return sb.ToString();
        }

        private static string GenerateSecurityScore(PEAnalyzer.PEInfo peInfo, AntiCheatDetector.DetectionResult acResult)
        {
            // Calculate security score (0-100)
            int score = 100;

            // Deduct points for missing security features
            if (!peInfo.HasASLR) score -= 10;
            if (!peInfo.HasDEP) score -= 10;
            if (!peInfo.HasCFG) score -= 5;
            if (!peInfo.HasSEH) score -= 5;
            if (!peInfo.HasAuthenticode) score -= 5;

            // Deduct for suspicious indicators
            score -= Math.Min(20, peInfo.SuspiciousIndicators.Count * 2);

            // Deduct for MITRE patterns
            score -= Math.Min(15, peInfo.MITREPatterns.Count * 5);

            // Deduct for packers
            score -= Math.Min(10, peInfo.DetectedPackers.Count * 3);

            // Deduct for TLS callbacks
            if (peInfo.HasTLSCallbacks) score -= 5;

            score = Math.Max(0, score);

            var sb = new StringBuilder();
            sb.AppendLine("        <div class='section-card'>");
            sb.AppendLine("            <h2>🎯 Security Assessment Score</h2>");
            sb.AppendLine("            <div class='security-score-container'>");

            string scoreClass = score >= 80 ? "score-excellent" : (score >= 60 ? "score-good" : (score >= 40 ? "score-warning" : "score-danger"));
            sb.AppendLine($"                <div class='security-score {scoreClass}'>");
            sb.AppendLine($"                    <div class='score-value'>{score}</div>");
            sb.AppendLine("                    <div class='score-label'>Security Score</div>");
            sb.AppendLine("                </div>");

            sb.AppendLine("                <div class='score-breakdown'>");
            sb.AppendLine("                    <h4>Score Breakdown:</h4>");
            sb.AppendLine("                    <ul>");
            if (!peInfo.HasASLR) sb.AppendLine("                        <li class='score-negative'>❌ No ASLR (-10 points)</li>");
            if (!peInfo.HasDEP) sb.AppendLine("                        <li class='score-negative'>❌ No DEP (-10 points)</li>");
            if (!peInfo.HasCFG) sb.AppendLine("                        <li class='score-negative'>❌ No CFG (-5 points)</li>");
            if (!peInfo.HasAuthenticode) sb.AppendLine("                        <li class='score-negative'>❌ Not signed (-5 points)</li>");
            if (peInfo.SuspiciousIndicators.Count > 0) sb.AppendLine($"                        <li class='score-negative'>⚠️ {peInfo.SuspiciousIndicators.Count} suspicious indicators (-{Math.Min(20, peInfo.SuspiciousIndicators.Count * 2)} points)</li>");
            if (peInfo.MITREPatterns.Count > 0) sb.AppendLine($"                        <li class='score-negative'>🎯 {peInfo.MITREPatterns.Count} MITRE techniques (-{Math.Min(15, peInfo.MITREPatterns.Count * 5)} points)</li>");
            if (peInfo.DetectedPackers.Count > 0) sb.AppendLine($"                        <li class='score-negative'>📦 {peInfo.DetectedPackers.Count} packers detected (-{Math.Min(10, peInfo.DetectedPackers.Count * 3)} points)</li>");

            if (score >= 80)
            {
                sb.AppendLine("                        <li class='score-positive'>✅ Strong security posture</li>");
            }
            sb.AppendLine("                    </ul>");
            sb.AppendLine("                </div>");

            sb.AppendLine("            </div>");
            sb.AppendLine("        </div>");
            return sb.ToString();
        }

        private static string GenerateImportsTab(PEAnalyzer.PEInfo peInfo)
        {
            var sb = new StringBuilder();
            sb.AppendLine("        <div id='imports' class='tab-content active'>");
            sb.AppendLine("            <h2>📦 Import Table Analysis</h2>");

            // Stats
            int totalFuncs = peInfo.Imports.Sum(i => i.Functions.Count);
            sb.AppendLine("            <div class='stats-row'>");
            sb.AppendLine($"                <div class='stat-item'><strong>{peInfo.Imports.Count}</strong> DLLs</div>");
            sb.AppendLine($"                <div class='stat-item'><strong>{totalFuncs}</strong> Functions</div>");
            sb.AppendLine($"                <div class='stat-item'><strong>{peInfo.OrdinalOnlyImports}</strong> Ordinal-Only</div>");
            if (peInfo.HasBoundImports)
            {
                int boundCount = peInfo.Imports.Count(i => i.IsBound);
                sb.AppendLine($"                <div class='stat-item status-info'><strong>{boundCount}</strong> Bound Imports</div>");
            }
            sb.AppendLine("            </div>");

            if (peInfo.OrdinalOnlyImports > 0)
            {
                sb.AppendLine("            <div class='alert alert-warning'>");
                sb.AppendLine($"                ⚠️ <strong>{peInfo.OrdinalOnlyImports} ordinal-only imports detected!</strong> This is often used for obfuscation.");
                sb.AppendLine("            </div>");
            }

            // Group by category
            var grouped = peInfo.Imports.GroupBy(i => i.Category).OrderBy(g => g.Key);
            foreach (var group in grouped)
            {
                sb.AppendLine($"            <div class='import-category'>");
                sb.AppendLine($"                <h3>{EscapeHtml(group.Key)}</h3>");

                foreach (var dll in group.OrderBy(d => d.DLLName))
                {
                    string boundBadge = dll.IsBound ? "<span class='badge badge-info'>BOUND</span>" : "";
                    sb.AppendLine($"                <div class='import-dll'>");
                    sb.AppendLine($"                    <strong>{EscapeHtml(dll.DLLName)}</strong> {boundBadge} <span class='func-count'>({dll.Functions.Count} functions)</span>");

                    // Show MITRE techniques for this DLL
                    var mitreForDLL = dll.DetailedFunctions.Where(f => !string.IsNullOrEmpty(f.MITRETechnique)).Select(f => f.MITRETechnique).Distinct().ToList();
                    if (mitreForDLL.Count > 0)
                    {
                        sb.AppendLine("                    <div class='mitre-badges'>");
                        foreach (var mitre in mitreForDLL)
                        {
                            sb.AppendLine($"                        <span class='badge badge-danger'>{EscapeHtml(mitre)}</span>");
                        }
                        sb.AppendLine("                    </div>");
                    }

                    sb.AppendLine($"                    <div class='function-list'>{EscapeHtml(string.Join(", ", dll.Functions.Take(10)))}{(dll.Functions.Count > 10 ? $"... (+{dll.Functions.Count - 10} more)" : "")}</div>");
                    sb.AppendLine("                </div>");
                }
                sb.AppendLine("            </div>");
            }

            sb.AppendLine("        </div>");
            return sb.ToString();
        }

        private static string GenerateExportsTab(PEAnalyzer.PEInfo peInfo)
        {
            var sb = new StringBuilder();
            sb.AppendLine("        <div id='exports' class='tab-content'>");
            sb.AppendLine("            <h2>📤 Export Table Analysis</h2>");

            if (peInfo.Exports.Count == 0)
            {
                sb.AppendLine("            <div class='alert alert-info'>");
                sb.AppendLine("                ℹ️ No exports found. This is normal for executables (EXE files). Only DLLs typically export functions.");
                sb.AppendLine("            </div>");
            }
            else
            {
                int forwardedCount = peInfo.Exports.Count(e => e.IsForwarded);
                sb.AppendLine("            <div class='stats-row'>");
                sb.AppendLine($"                <div class='stat-item'><strong>{peInfo.Exports.Count}</strong> Exports</div>");
                if (forwardedCount > 0)
                {
                    sb.AppendLine($"                <div class='stat-item status-warning'><strong>{forwardedCount}</strong> Forwarded</div>");
                }
                sb.AppendLine("            </div>");

                sb.AppendLine("            <table class='data-table'>");
                sb.AppendLine("                <thead>");
                sb.AppendLine("                    <tr><th>Function Name</th><th>Ordinal</th><th>RVA</th><th>Forwarded To</th></tr>");
                sb.AppendLine("                </thead>");
                sb.AppendLine("                <tbody>");

                foreach (var exp in peInfo.Exports.OrderBy(e => e.Name))
                {
                    string forwardedCell = exp.IsForwarded ? $"<span class='badge badge-warning'>→ {EscapeHtml(exp.ForwarderChain)}</span>" : "-";
                    string rowClass = exp.IsForwarded ? "forwarded-export" : "";
                    sb.AppendLine($"                    <tr class='{rowClass}'>");
                    sb.AppendLine($"                        <td><strong>{EscapeHtml(exp.Name)}</strong></td>");
                    sb.AppendLine($"                        <td>{exp.Ordinal}</td>");
                    sb.AppendLine($"                        <td class='monospace'>0x{exp.RVA:X8}</td>");
                    sb.AppendLine($"                        <td>{forwardedCell}</td>");
                    sb.AppendLine("                    </tr>");
                }

                sb.AppendLine("                </tbody>");
                sb.AppendLine("            </table>");
            }

            sb.AppendLine("        </div>");
            return sb.ToString();
        }

        private static string GenerateDelayImportsTab(PEAnalyzer.PEInfo peInfo)
        {
            var sb = new StringBuilder();
            sb.AppendLine("        <div id='delay' class='tab-content'>");
            sb.AppendLine("            <h2>⏱️ Delay-Load Imports</h2>");

            if (peInfo.DelayImports.Count == 0)
            {
                sb.AppendLine("            <div class='alert alert-info'>");
                sb.AppendLine("                ℹ️ No delay-load imports found. All DLLs are loaded at startup.");
                sb.AppendLine("            </div>");
            }
            else
            {
                sb.AppendLine("            <div class='alert alert-warning'>");
                sb.AppendLine($"                ⚠️ <strong>{peInfo.DelayImports.Count} delay-load DLLs detected.</strong> These are loaded on first use, which can be used for optimization or to hide suspicious imports.");
                sb.AppendLine("            </div>");

                foreach (var delay in peInfo.DelayImports)
                {
                    sb.AppendLine("            <div class='delay-import-card'>");
                    sb.AppendLine($"                <h3>{EscapeHtml(delay.DLLName)} <span class='badge badge-warning'>DELAY-LOADED</span></h3>");
                    sb.AppendLine($"                <p class='delay-reason'>{EscapeHtml(delay.Reason)}</p>");
                    sb.AppendLine($"                <div class='function-list'><strong>Functions ({delay.Functions.Count}):</strong> {EscapeHtml(string.Join(", ", delay.Functions.Take(15)))}{(delay.Functions.Count > 15 ? $"... (+{delay.Functions.Count - 15} more)" : "")}</div>");
                    sb.AppendLine("            </div>");
                }
            }

            sb.AppendLine("        </div>");
            return sb.ToString();
        }

        private static string GenerateSectionsTab(PEAnalyzer.PEInfo peInfo)
        {
            var sb = new StringBuilder();
            sb.AppendLine("        <div id='sections' class='tab-content'>");
            sb.AppendLine("            <h2>📊 Section Analysis</h2>");

            sb.AppendLine("            <table class='data-table'>");
            sb.AppendLine("                <thead>");
            sb.AppendLine("                    <tr><th>Name</th><th>Virtual Address</th><th>Virtual Size</th><th>Raw Size</th><th>Entropy</th><th>Flags</th></tr>");
            sb.AppendLine("                </thead>");
            sb.AppendLine("                <tbody>");

            foreach (var section in peInfo.Sections)
            {
                string entropyClass = section.Entropy > 7.2 ? "entropy-high" : (section.Entropy > 6.0 ? "entropy-medium" : "entropy-low");
                string entropyWarning = section.Entropy > 7.2 ? "⚠️ Packed/Encrypted" : "";

                sb.AppendLine("                    <tr>");
                sb.AppendLine($"                        <td><strong>{EscapeHtml(section.Name)}</strong></td>");
                sb.AppendLine($"                        <td class='monospace'>0x{section.VirtualAddress:X8}</td>");
                sb.AppendLine($"                        <td>{section.VirtualSize:N0} bytes</td>");
                sb.AppendLine($"                        <td>{section.RawSize:N0} bytes</td>");
                sb.AppendLine($"                        <td class='{entropyClass}'><strong>{section.Entropy:F2}</strong> {entropyWarning}</td>");
                sb.AppendLine($"                        <td class='flags'>{EscapeHtml(section.Flags)}</td>");
                sb.AppendLine("                    </tr>");
            }

            sb.AppendLine("                </tbody>");
            sb.AppendLine("            </table>");

            if (peInfo.HasOverlay)
            {
                sb.AppendLine("            <div class='alert alert-warning'>");
                sb.AppendLine($"                ⚠️ <strong>Overlay detected:</strong> {peInfo.OverlaySize:N0} bytes of data after PE sections. May contain resources, data, or hidden payloads.");
                sb.AppendLine("            </div>");
            }

            sb.AppendLine("        </div>");
            return sb.ToString();
        }

        private static string GenerateRichHeaderTab(PEAnalyzer.PEInfo peInfo)
        {
            var sb = new StringBuilder();
            sb.AppendLine("        <div id='richheader' class='tab-content'>");
            sb.AppendLine("            <h2>🛠️ Rich Header Analysis</h2>");

            if (peInfo.RichHeader == null || !peInfo.RichHeader.IsValid)
            {
                sb.AppendLine("            <div class='alert alert-warning'>");
                sb.AppendLine("                ⚠️ <strong>No Rich Header found or invalid.</strong> This could indicate:");
                sb.AppendLine("                <ul>");
                sb.AppendLine("                    <li>Non-MSVC compiler was used (GCC, MinGW, etc.)</li>");
                sb.AppendLine("                    <li>Header was stripped/tampered with</li>");
                sb.AppendLine("                    <li>Binary was packed</li>");
                sb.AppendLine("                </ul>");
                sb.AppendLine("            </div>");
            }
            else
            {
                if (peInfo.RichHeader.IsTampered)
                {
                    sb.AppendLine("            <div class='alert alert-danger'>");
                    sb.AppendLine("                🚨 <strong>Rich Header tampering detected!</strong> Checksum validation failed.");
                    sb.AppendLine("            </div>");
                }

                sb.AppendLine("            <div class='rich-header-info'>");
                sb.AppendLine($"                <p><strong>Checksum:</strong> <span class='monospace'>{peInfo.RichHeader.Checksum}</span></p>");
                sb.AppendLine($"                <p><strong>Detected Compilers:</strong> {peInfo.RichHeader.Compilers.Count}</p>");
                sb.AppendLine("            </div>");

                sb.AppendLine("            <h3>Compiler/Linker Tools Used</h3>");
                sb.AppendLine("            <table class='data-table'>");
                sb.AppendLine("                <thead>");
                sb.AppendLine("                    <tr><th>Product Name</th><th>Product ID</th><th>Build Number</th><th>Use Count</th></tr>");
                sb.AppendLine("                </thead>");
                sb.AppendLine("                <tbody>");

                foreach (var compiler in peInfo.RichHeader.Compilers.OrderByDescending(c => c.UseCount))
                {
                    sb.AppendLine("                    <tr>");
                    sb.AppendLine($"                        <td><strong>{EscapeHtml(compiler.ProductName)}</strong></td>");
                    sb.AppendLine($"                        <td class='monospace'>0x{compiler.ProductId:X4}</td>");
                    sb.AppendLine($"                        <td>{compiler.BuildNumber}</td>");
                    sb.AppendLine($"                        <td><span class='badge badge-info'>{compiler.UseCount} objects</span></td>");
                    sb.AppendLine("                    </tr>");
                }

                sb.AppendLine("                </tbody>");
                sb.AppendLine("            </table>");

                // Show primary compiler
                var primary = peInfo.RichHeader.Compilers.OrderByDescending(c => c.UseCount).FirstOrDefault();
                if (primary != null)
                {
                    sb.AppendLine("            <div class='alert alert-info'>");
                    sb.AppendLine($"                ℹ️ <strong>Primary Build Tool:</strong> {EscapeHtml(primary.ProductName)} (Build {primary.BuildNumber}) - Used for {primary.UseCount} object files");
                    sb.AppendLine("            </div>");
                }
            }

            sb.AppendLine("        </div>");
            return sb.ToString();
        }

        private static string GenerateDependenciesTab(PEAnalyzer.PEInfo peInfo)
        {
            var sb = new StringBuilder();
            sb.AppendLine("        <div id='dependencies' class='tab-content'>");
            sb.AppendLine("            <h2>🔗 Dependency Analysis</h2>");

            if (peInfo.Dependencies == null)
            {
                sb.AppendLine("            <div class='alert alert-info'>");
                sb.AppendLine("                ℹ️ Dependency analysis not available.");
                sb.AppendLine("            </div>");
            }
            else
            {
                sb.AppendLine("            <div class='stats-row'>");
                sb.AppendLine($"                <div class='stat-item'><strong>{peInfo.Dependencies.TotalDependencies}</strong> Dependencies</div>");
                sb.AppendLine($"                <div class='stat-item'><strong>{peInfo.Dependencies.MaxDepth}</strong> Max Depth</div>");
                if (peInfo.Dependencies.MissingDependencies.Count > 0)
                {
                    sb.AppendLine($"                <div class='stat-item status-warning'><strong>{peInfo.Dependencies.MissingDependencies.Count}</strong> Missing</div>");
                }
                if (peInfo.Dependencies.CircularDependencies.Count > 0)
                {
                    sb.AppendLine($"                <div class='stat-item status-danger'><strong>{peInfo.Dependencies.CircularDependencies.Count}</strong> Circular</div>");
                }
                sb.AppendLine("            </div>");

                if (peInfo.Dependencies.MissingDependencies.Count > 0)
                {
                    sb.AppendLine("            <div class='alert alert-warning'>");
                    sb.AppendLine("                ⚠️ <strong>Missing Dependencies Detected:</strong>");
                    sb.AppendLine("                <ul>");
                    foreach (var missing in peInfo.Dependencies.MissingDependencies)
                    {
                        sb.AppendLine($"                    <li>{EscapeHtml(missing)}</li>");
                    }
                    sb.AppendLine("                </ul>");
                    sb.AppendLine("            </div>");
                }

                sb.AppendLine("            <h3>Dependency Tree</h3>");
                sb.AppendLine("            <div class='dependency-tree'>");

                foreach (var dep in peInfo.Dependencies.DependencyTree.OrderByDescending(d => d.Value))
                {
                    int barWidth = peInfo.Dependencies.DependencyTree.Values.Max() > 0
                        ? (dep.Value * 100 / peInfo.Dependencies.DependencyTree.Values.Max())
                        : 0;

                    sb.AppendLine("                <div class='dependency-item'>");
                    sb.AppendLine($"                    <div class='dependency-name'>{EscapeHtml(dep.Key)}</div>");
                    sb.AppendLine("                    <div class='dependency-bar-container'>");
                    sb.AppendLine($"                        <div class='dependency-bar' style='width: {barWidth}%'></div>");
                    sb.AppendLine($"                        <span class='dependency-count'>{dep.Value} functions</span>");
                    sb.AppendLine("                    </div>");
                    sb.AppendLine("                </div>");
                }

                sb.AppendLine("            </div>");
            }

            sb.AppendLine("        </div>");
            return sb.ToString();
        }

        private static string GenerateMITRETab(PEAnalyzer.PEInfo peInfo)
        {
            var sb = new StringBuilder();
            sb.AppendLine("        <div id='mitre' class='tab-content'>");
            sb.AppendLine("            <h2>🎯 MITRE ATT&CK Techniques</h2>");

            if (peInfo.MITREPatterns.Count == 0)
            {
                sb.AppendLine("            <div class='alert alert-success'>");
                sb.AppendLine("                ✅ <strong>No known MITRE ATT&CK techniques detected.</strong> Import patterns appear benign.");
                sb.AppendLine("            </div>");
            }
            else
            {
                sb.AppendLine("            <div class='alert alert-danger'>");
                sb.AppendLine($"                🚨 <strong>{peInfo.MITREPatterns.Count} MITRE ATT&CK techniques detected!</strong> This binary uses APIs associated with potentially malicious behavior.");
                sb.AppendLine("            </div>");

                sb.AppendLine("            <div class='mitre-grid'>");

                foreach (var technique in peInfo.MITREPatterns.OrderBy(m => m))
                {
                    var parts = technique.Split(" - ");
                    string techniqueId = parts.Length > 0 ? parts[0] : "";
                    string techniqueName = parts.Length > 1 ? parts[1] : technique;
                    string severityClass = GetMITRESeverityClass(techniqueId);

                    sb.AppendLine($"                <div class='mitre-card {severityClass}'>");
                    sb.AppendLine($"                    <div class='mitre-id'>{EscapeHtml(techniqueId)}</div>");
                    sb.AppendLine($"                    <div class='mitre-name'>{EscapeHtml(techniqueName)}</div>");
                    sb.AppendLine($"                    <div class='mitre-description'>{GetMITREDescription(techniqueId)}</div>");
                    sb.AppendLine($"                    <a href='https://attack.mitre.org/techniques/{techniqueId.Replace(".", "/")}/' target='_blank' class='mitre-link'>View on MITRE →</a>");
                    sb.AppendLine("                </div>");
                }

                sb.AppendLine("            </div>");
            }

            sb.AppendLine("        </div>");
            return sb.ToString();
        }

        private static string GenerateAntiCheatTab(AntiCheatDetector.DetectionResult acResult)
        {
            var sb = new StringBuilder();
            sb.AppendLine("        <div id='anticheat' class='tab-content'>");
            sb.AppendLine("            <h2>🛡️ Anti-Cheat Detection</h2>");

            if (acResult.DetectedAntiCheats.Count == 0)
            {
                sb.AppendLine("            <div class='alert alert-success'>");
                sb.AppendLine("                ✅ <strong>No anti-cheat systems detected.</strong>");
                sb.AppendLine("            </div>");
            }
            else
            {
                sb.AppendLine($"            <div class='alert alert-danger'>");
                sb.AppendLine($"                🚨 <strong>{acResult.DetectedAntiCheats.Count} anti-cheat system(s) detected!</strong> Overall threat level: <strong>{acResult.OverallThreat}</strong>");
                sb.AppendLine("            </div>");

                foreach (var ac in acResult.DetectedAntiCheats.OrderByDescending(a => a.Severity))
                {
                    string severityClass = ac.Severity switch
                    {
                        "Extreme" => "severity-extreme",
                        "High" => "severity-high",
                        "Medium" => "severity-medium",
                        _ => "severity-low"
                    };

                    sb.AppendLine($"            <div class='anticheat-card {severityClass}'>");
                    sb.AppendLine($"                <div class='anticheat-header'>");
                    sb.AppendLine($"                    <h3>{EscapeHtml(ac.Name)}{(ac.IsCustom ? " <span class='badge badge-custom'>CUSTOM</span>" : "")}</h3>");
                    sb.AppendLine($"                    <span class='badge badge-{severityClass}'>{ac.Severity}</span>");
                    sb.AppendLine("                </div>");
                    sb.AppendLine($"                <p class='anticheat-type'><strong>Type:</strong> {ac.Type}{(ac.IsCustom ? " (Homebrew/Custom)" : "")}</p>");
                    sb.AppendLine($"                <p class='anticheat-type'><strong>Version:</strong> {EscapeHtml(ac.Version)}</p>");
                    sb.AppendLine($"                <p class='anticheat-desc'>{EscapeHtml(ac.Description)}</p>");
                    sb.AppendLine("                <div class='anticheat-components'>");
                    sb.AppendLine("                    <strong>Detected Components:</strong>");
                    sb.AppendLine("                    <ul>");
                    foreach (var component in ac.DetectedComponents)
                    {
                        sb.AppendLine($"                        <li>{EscapeHtml(component)}</li>");
                    }
                    sb.AppendLine("                    </ul>");
                    sb.AppendLine("                </div>");
                    sb.AppendLine("            </div>");
                }
            }

            sb.AppendLine("        </div>");
            return sb.ToString();
        }

        private static string GenerateSecurityTab(PEAnalyzer.PEInfo peInfo)
        {
            var sb = new StringBuilder();
            sb.AppendLine("        <div id='security' class='tab-content'>");
            sb.AppendLine("            <h2>🔒 Security Features & Analysis</h2>");

            // Security Features
            sb.AppendLine("            <div class='security-features'>");
            sb.AppendLine("                <h3>Security Mitigations</h3>");
            sb.AppendLine("                <div class='feature-grid'>");

            AddSecurityFeature(sb, "ASLR", "Address Space Layout Randomization", peInfo.HasASLR,
                "Memory addresses are randomized, making exploits harder.",
                "Predictable memory layout makes exploitation easier!");

            AddSecurityFeature(sb, "DEP", "Data Execution Prevention", peInfo.HasDEP,
                "Prevents code execution from data sections.",
                "Code can execute from data/stack!");

            AddSecurityFeature(sb, "CFG", "Control Flow Guard", peInfo.HasCFG,
                "Function pointers are validated, preventing hijacking.",
                "No control flow validation.");

            AddSecurityFeature(sb, "SEH", "Structured Exception Handling", peInfo.HasSEH,
                "Exception handlers are protected.",
                "No SEH protection (NO_SEH flag set).");

            AddSecurityFeature(sb, "Authenticode", "Digital Signature", peInfo.HasAuthenticode,
                $"File is signed: {peInfo.SignatureInfo}",
                "File is not digitally signed.");

            sb.AppendLine("                </div>");
            sb.AppendLine("            </div>");

            // Packers
            if (peInfo.DetectedPackers.Count > 0)
            {
                sb.AppendLine("            <div class='alert alert-warning'>");
                sb.AppendLine("                ⚠️ <strong>Detected Packers/Protectors:</strong>");
                sb.AppendLine("                <ul>");
                foreach (var packer in peInfo.DetectedPackers)
                {
                    sb.AppendLine($"                    <li>{EscapeHtml(packer)}</li>");
                }
                sb.AppendLine("                </ul>");
                sb.AppendLine("                <p>Packed executables may contain obfuscated or encrypted code.</p>");
                sb.AppendLine("            </div>");
            }

            // Suspicious Indicators
            if (peInfo.SuspiciousIndicators.Count > 0)
            {
                sb.AppendLine("            <div class='alert alert-danger'>");
                sb.AppendLine($"                🚨 <strong>{peInfo.SuspiciousIndicators.Count} Suspicious Indicators Detected:</strong>");
                sb.AppendLine("                <ul>");
                foreach (var indicator in peInfo.SuspiciousIndicators.Take(25))
                {
                    sb.AppendLine($"                    <li>{EscapeHtml(indicator)}</li>");
                }
                if (peInfo.SuspiciousIndicators.Count > 25)
                {
                    sb.AppendLine($"                    <li><em>... and {peInfo.SuspiciousIndicators.Count - 25} more indicators</em></li>");
                }
                sb.AppendLine("                </ul>");
                sb.AppendLine("            </div>");
            }

            sb.AppendLine("        </div>");
            return sb.ToString();
        }

        private static string GenerateVersionTab(PEAnalyzer.PEInfo peInfo)
        {
            var sb = new StringBuilder();
            sb.AppendLine("        <div id='version' class='tab-content'>");
            sb.AppendLine("            <h2>ℹ️ PE File Information</h2>");

            sb.AppendLine("            <div class='info-grid'>");

            // Basic Info
            sb.AppendLine("            <div class='info-section'>");
            sb.AppendLine("                <h3>Basic Information</h3>");
            sb.AppendLine($"                <p><strong>File Path:</strong> {EscapeHtml(peInfo.FilePath)}</p>");
            sb.AppendLine($"                <p><strong>Architecture:</strong> {(peInfo.Is64Bit ? "x64 (64-bit)" : "x86 (32-bit)")}</p>");
            sb.AppendLine($"                <p><strong>Subsystem:</strong> {EscapeHtml(peInfo.SubsystemName)}</p>");
            sb.AppendLine($"                <p><strong>Image Base:</strong> <span class='monospace'>0x{peInfo.ImageBase:X}</span></p>");
            sb.AppendLine($"                <p><strong>Entry Point:</strong> <span class='monospace'>0x{peInfo.EntryPoint:X}</span></p>");
            sb.AppendLine($"                <p><strong>Compilation Time:</strong> {peInfo.CompilationTime:yyyy-MM-dd HH:mm:ss} UTC</p>");
            sb.AppendLine("            </div>");

            // Hashes & Identifiers
            sb.AppendLine("            <div class='info-section'>");
            sb.AppendLine("                <h3>Hashes & Identifiers</h3>");
            sb.AppendLine($"                <p><strong>Import Hash:</strong> <span class='monospace'>{EscapeHtml(peInfo.ImpHash)}</span> <button class='copy-btn-small' onclick='copyToClipboard(\"{peInfo.ImpHash}\")'>Copy</button></p>");
            if (!string.IsNullOrEmpty(peInfo.CompilerInfo))
            {
                sb.AppendLine($"                <p><strong>Compiler:</strong> {EscapeHtml(peInfo.CompilerInfo)}</p>");
            }
            sb.AppendLine($"                <p><strong>Digital Signature:</strong> {EscapeHtml(peInfo.SignatureInfo)}</p>");
            sb.AppendLine("            </div>");

            // Statistics
            sb.AppendLine("            <div class='info-section'>");
            sb.AppendLine("                <h3>Statistics</h3>");
            sb.AppendLine($"                <p><strong>Total Imports:</strong> {peInfo.Imports.Count} DLLs, {peInfo.Imports.Sum(i => i.Functions.Count)} functions</p>");
            sb.AppendLine($"                <p><strong>Total Exports:</strong> {peInfo.Exports.Count} functions</p>");
            sb.AppendLine($"                <p><strong>Total Sections:</strong> {peInfo.Sections.Count}</p>");
            sb.AppendLine($"                <p><strong>TLS Callbacks:</strong> {(peInfo.HasTLSCallbacks ? "⚠️ YES (Anti-debugging)" : "No")}</p>");
            if (peInfo.HasOverlay)
            {
                sb.AppendLine($"                <p><strong>Overlay Data:</strong> {peInfo.OverlaySize:N0} bytes</p>");
            }
            if (peInfo.HasDelayLoadImports)
            {
                sb.AppendLine($"                <p><strong>Delay-Load Imports:</strong> {peInfo.DelayImports.Count} DLLs</p>");
            }
            sb.AppendLine("            </div>");

            // Version Information (if available)
            if (peInfo.FileVersion != null)
            {
                sb.AppendLine("            <div class='info-section full-width'>");
                sb.AppendLine("                <h3>Version Resource Information</h3>");
                if (!string.IsNullOrEmpty(peInfo.FileVersion.FileVersion))
                    sb.AppendLine($"                <p><strong>File Version:</strong> {EscapeHtml(peInfo.FileVersion.FileVersion)}</p>");
                if (!string.IsNullOrEmpty(peInfo.FileVersion.ProductVersion))
                    sb.AppendLine($"                <p><strong>Product Version:</strong> {EscapeHtml(peInfo.FileVersion.ProductVersion)}</p>");
                if (!string.IsNullOrEmpty(peInfo.FileVersion.CompanyName))
                    sb.AppendLine($"                <p><strong>Company:</strong> {EscapeHtml(peInfo.FileVersion.CompanyName)}</p>");
                if (!string.IsNullOrEmpty(peInfo.FileVersion.FileDescription))
                    sb.AppendLine($"                <p><strong>Description:</strong> {EscapeHtml(peInfo.FileVersion.FileDescription)}</p>");
                if (!string.IsNullOrEmpty(peInfo.FileVersion.ProductName))
                    sb.AppendLine($"                <p><strong>Product Name:</strong> {EscapeHtml(peInfo.FileVersion.ProductName)}</p>");
                if (!string.IsNullOrEmpty(peInfo.FileVersion.LegalCopyright))
                    sb.AppendLine($"                <p><strong>Copyright:</strong> {EscapeHtml(peInfo.FileVersion.LegalCopyright)}</p>");
                if (!string.IsNullOrEmpty(peInfo.FileVersion.OriginalFilename))
                    sb.AppendLine($"                <p><strong>Original Filename:</strong> {EscapeHtml(peInfo.FileVersion.OriginalFilename)}</p>");
                sb.AppendLine("            </div>");
            }

            sb.AppendLine("            </div>");
            sb.AppendLine("        </div>");
            return sb.ToString();
        }

        private static void AddSecurityFeature(StringBuilder sb, string name, string fullName, bool enabled, string enabledDesc, string disabledDesc)
        {
            string statusClass = enabled ? "feature-enabled" : "feature-disabled";
            string icon = enabled ? "✅" : "❌";
            string statusText = enabled ? "ENABLED" : "DISABLED";
            string description = enabled ? enabledDesc : disabledDesc;

            sb.AppendLine($"                <div class='security-feature {statusClass}'>");
            sb.AppendLine($"                    <div class='feature-header'>");
            sb.AppendLine($"                        <h4>{icon} {name}</h4>");
            sb.AppendLine($"                        <span class='feature-status'>{statusText}</span>");
            sb.AppendLine("                    </div>");
            sb.AppendLine($"                    <p class='feature-name'>{fullName}</p>");
            sb.AppendLine($"                    <p class='feature-desc'>{description}</p>");
            sb.AppendLine("                </div>");
        }

        // Helper methods
        private static string EscapeHtml(string? text)
        {
            if (string.IsNullOrEmpty(text)) return "";
            return text.Replace("&", "&amp;")
                       .Replace("<", "&lt;")
                       .Replace(">", "&gt;")
                       .Replace("\"", "&quot;")
                       .Replace("'", "&#39;");
        }

        private static string GetCategoryClass(string category)
        {
            return category switch
            {
                "Process/Thread" => "cat-process",
                "File Operations" => "cat-file",
                "Network" => "cat-network",
                "Registry" => "cat-registry",
                "Cryptography" => "cat-crypto",
                "Debugging" => "cat-debug",
                "Memory" => "cat-memory",
                _ => "cat-other"
            };
        }

        private static string GetMITRESeverityClass(string techniqueId)
        {
            // High severity techniques
            if (techniqueId.Contains("T1055") || techniqueId.Contains("T1486") || techniqueId.Contains("T1105"))
                return "mitre-critical";

            // Medium severity
            if (techniqueId.Contains("T1622") || techniqueId.Contains("T1112") || techniqueId.Contains("T1056"))
                return "mitre-high";

            return "mitre-medium";
        }

        private static string GetMITREDescription(string techniqueId)
        {
            return techniqueId switch
            {
                "T1055" => "Injecting code into other processes to evade detection and maintain persistence.",
                "T1622" => "Detecting and evading debugging tools to hinder analysis.",
                "T1112" => "Modifying Windows Registry for persistence or configuration changes.",
                "T1543" => "Creating or modifying system services for persistence.",
                "T1105" => "Downloading tools or malicious files from external sources.",
                "T1056" => "Capturing user input such as keystrokes or mouse activity.",
                "T1486" => "Encrypting data to render it unusable (ransomware behavior).",
                "T1057" => "Enumerating running processes to identify targets or security tools.",
                "T1179" => "Installing hooks to intercept system or application calls.",
                "T1106" => "Executing system commands or APIs directly.",
                _ => "Advanced technique detected."
            };
        }

        private static string GetCSS()
        {
            return @"
* {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
}

body {
    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
    background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
    min-height: 100vh;
    padding: 20px;
    color: #333;
}

.header {
    background: white;
    border-radius: 12px;
    padding: 30px;
    margin-bottom: 20px;
    text-align: center;
    box-shadow: 0 4px 15px rgba(0,0,0,0.1);
}

.header h1 {
    color: #667eea;
    font-size: 2.5em;
    margin-bottom: 10px;
}

.header h2 {
    color: #555;
    font-size: 1.5em;
    margin-bottom: 10px;
}

.timestamp {
    color: #888;
    font-size: 0.9em;
}

.container {
    max-width: 1400px;
    margin: 0 auto;
}

.summary-grid {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
    gap: 20px;
    margin-bottom: 30px;
}

.card {
    background: white;
    border-radius: 12px;
    padding: 25px;
    box-shadow: 0 4px 15px rgba(0,0,0,0.1);
    transition: transform 0.3s ease, box-shadow 0.3s ease;
    display: flex;
    align-items: center;
    gap: 20px;
}

.card:hover {
    transform: translateY(-5px);
    box-shadow: 0 6px 20px rgba(0,0,0,0.15);
}

.card-icon {
    font-size: 3em;
}

.card-content h3 {
    color: #555;
    font-size: 0.9em;
    margin-bottom: 10px;
    text-transform: uppercase;
    letter-spacing: 1px;
}

.card-value {
    font-size: 2em;
    font-weight: bold;
    color: #667eea;
}

.card-value-small {
    font-size: 1.2em;
    font-weight: bold;
    color: #667eea;
}

.card-detail {
    font-size: 0.85em;
    color: #888;
    margin-top: 5px;
}

.section-card {
    background: white;
    border-radius: 12px;
    padding: 30px;
    margin-bottom: 20px;
    box-shadow: 0 4px 15px rgba(0,0,0,0.1);
}

.section-card h2 {
    color: #667eea;
    margin-bottom: 20px;
    border-bottom: 2px solid #f0f0f0;
    padding-bottom: 10px;
}

/* API Categories */
.api-categories {
    display: flex;
    flex-direction: column;
    gap: 15px;
}

.api-category-item {
    display: flex;
    flex-direction: column;
    gap: 5px;
}

.api-category-label {
    display: flex;
    justify-content: space-between;
    font-weight: 600;
    color: #555;
}

.api-count {
    background: #667eea;
    color: white;
    padding: 2px 8px;
    border-radius: 12px;
    font-size: 0.85em;
}

.api-category-bar {
    background: #f0f0f0;
    border-radius: 8px;
    height: 25px;
    overflow: hidden;
}

.api-category-fill {
    height: 100%;
    transition: width 0.5s ease;
    display: flex;
    align-items: center;
    padding-left: 10px;
    color: white;
    font-weight: bold;
    font-size: 0.85em;
}

.cat-process { background: linear-gradient(90deg, #f093fb 0%, #f5576c 100%); }
.cat-file { background: linear-gradient(90deg, #4facfe 0%, #00f2fe 100%); }
.cat-network { background: linear-gradient(90deg, #43e97b 0%, #38f9d7 100%); }
.cat-registry { background: linear-gradient(90deg, #fa709a 0%, #fee140 100%); }
.cat-crypto { background: linear-gradient(90deg, #30cfd0 0%, #330867 100%); }
.cat-debug { background: linear-gradient(90deg, #a8edea 0%, #fed6e3 100%); }
.cat-memory { background: linear-gradient(90deg, #ffecd2 0%, #fcb69f 100%); }
.cat-other { background: linear-gradient(90deg, #667eea 0%, #764ba2 100%); }

/* Security Score */
.security-score-container {
    display: flex;
    gap: 30px;
    align-items: center;
    flex-wrap: wrap;
}

.security-score {
    width: 180px;
    height: 180px;
    border-radius: 50%;
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    box-shadow: 0 4px 15px rgba(0,0,0,0.2);
}

.score-excellent { background: linear-gradient(135deg, #11998e 0%, #38ef7d 100%); }
.score-good { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); }
.score-warning { background: linear-gradient(135deg, #f093fb 0%, #f5576c 100%); }
.score-danger { background: linear-gradient(135deg, #ee0979 0%, #ff6a00 100%); }

.score-value {
    font-size: 4em;
    font-weight: bold;
    color: white;
}

.score-label {
    color: white;
    font-size: 0.9em;
    text-transform: uppercase;
    letter-spacing: 1px;
}

.score-breakdown {
    flex: 1;
    min-width: 300px;
}

.score-breakdown h4 {
    margin-bottom: 15px;
    color: #667eea;
}

.score-breakdown ul {
    list-style: none;
}

.score-breakdown li {
    padding: 8px 0;
    border-bottom: 1px solid #f0f0f0;
}

.score-positive { color: #11998e; }
.score-negative { color: #ee0979; }

/* Tabs */
.tabs {
    display: flex;
    gap: 5px;
    flex-wrap: wrap;
    background: white;
    border-radius: 12px;
    padding: 10px;
    box-shadow: 0 4px 15px rgba(0,0,0,0.1);
    margin-bottom: 20px;
    position: sticky;
    top: 20px;
    z-index: 100;
}

.tab-btn {
    padding: 12px 20px;
    border: none;
    background: #f0f0f0;
    color: #555;
    border-radius: 8px;
    cursor: pointer;
    font-weight: 600;
    transition: all 0.3s ease;
    font-size: 0.95em;
}

.tab-btn:hover {
    background: #e0e0e0;
    transform: translateY(-2px);
}

.tab-btn.active {
    background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
    color: white;
    box-shadow: 0 4px 10px rgba(102, 126, 234, 0.3);
}

.tab-content {
    display: none;
    background: white;
    border-radius: 12px;
    padding: 30px;
    box-shadow: 0 4px 15px rgba(0,0,0,0.1);
    animation: fadeIn 0.3s ease;
}

.tab-content.active {
    display: block;
}

@keyframes fadeIn {
    from { opacity: 0; transform: translateY(10px); }
    to { opacity: 1; transform: translateY(0); }
}

.tab-content h2 {
    color: #667eea;
    margin-bottom: 25px;
    padding-bottom: 15px;
    border-bottom: 2px solid #f0f0f0;
}

/* Stats Row */
.stats-row {
    display: flex;
    gap: 20px;
    margin-bottom: 25px;
    flex-wrap: wrap;
}

.stat-item {
    background: #f8f9fa;
    padding: 15px 25px;
    border-radius: 8px;
    font-size: 0.95em;
    color: #555;
}

.stat-item strong {
    color: #667eea;
    font-size: 1.3em;
    display: block;
    margin-bottom: 5px;
}

/* Status Colors */
.status-good { color: #11998e !important; }
.status-info { color: #667eea !important; }
.status-warning { color: #f5576c !important; }
.status-danger { color: #ee0979 !important; }

/* Alerts */
.alert {
    padding: 20px;
    border-radius: 8px;
    margin-bottom: 20px;
    border-left: 4px solid;
}

.alert-success {
    background: #d4edda;
    border-color: #11998e;
    color: #155724;
}

.alert-info {
    background: #d1ecf1;
    border-color: #667eea;
    color: #0c5460;
}

.alert-warning {
    background: #fff3cd;
    border-color: #f5576c;
    color: #856404;
}

.alert-danger {
    background: #f8d7da;
    border-color: #ee0979;
    color: #721c24;
}

.alert ul {
    margin-top: 15px;
    margin-left: 20px;
}

.alert li {
    margin-bottom: 8px;
}

/* Tables */
.data-table {
    width: 100%;
    border-collapse: collapse;
    margin-top: 20px;
}

.data-table thead {
    background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
    color: white;
}

.data-table th {
    padding: 15px;
    text-align: left;
    font-weight: 600;
    text-transform: uppercase;
    font-size: 0.85em;
    letter-spacing: 1px;
}

.data-table td {
    padding: 12px 15px;
    border-bottom: 1px solid #f0f0f0;
}

.data-table tbody tr:hover {
    background: #f8f9fa;
}

.forwarded-export {
    background: #fff3cd !important;
}

/* Entropy highlighting */
.entropy-low { color: #11998e; font-weight: bold; }
.entropy-medium { color: #f5576c; font-weight: bold; }
.entropy-high { color: #ee0979; font-weight: bold; }

/* Import sections */
.import-category {
    margin-bottom: 30px;
}

.import-category h3 {
    color: #667eea;
    margin-bottom: 15px;
    padding: 10px;
    background: #f8f9fa;
    border-radius: 6px;
}

.import-dll {
    background: #f8f9fa;
    padding: 15px;
    border-radius: 8px;
    margin-bottom: 15px;
    border-left: 4px solid #667eea;
}

.import-dll strong {
    color: #667eea;
    font-size: 1.1em;
}

.func-count {
    color: #888;
    font-size: 0.9em;
}

.function-list {
    margin-top: 10px;
    color: #666;
    font-size: 0.9em;
    font-family: 'Consolas', 'Monaco', monospace;
}

/* Badges */
.badge {
    display: inline-block;
    padding: 4px 10px;
    border-radius: 12px;
    font-size: 0.8em;
    font-weight: 600;
    margin: 2px;
}

.badge-info { background: #667eea; color: white; }
.badge-warning { background: #f5576c; color: white; }
.badge-danger { background: #ee0979; color: white; }
.badge-success { background: #11998e; color: white; }
.badge-custom { background: #ff6b35; color: white; }

.mitre-badges {
    margin-top: 8px;
    display: flex;
    flex-wrap: wrap;
    gap: 5px;
}

/* Delay Import Cards */
.delay-import-card {
    background: #fff3cd;
    border-left: 4px solid #f5576c;
    padding: 20px;
    border-radius: 8px;
    margin-bottom: 20px;
}

.delay-import-card h3 {
    color: #856404;
    margin-bottom: 10px;
}

.delay-reason {
    color: #856404;
    font-style: italic;
    margin-bottom: 15px;
}

/* Rich Header */
.rich-header-info {
    background: #f8f9fa;
    padding: 20px;
    border-radius: 8px;
    margin-bottom: 20px;
}

.rich-header-info p {
    margin-bottom: 10px;
}

/* Dependency Tree */
.dependency-tree {
    margin-top: 20px;
}

.dependency-item {
    margin-bottom: 15px;
}

.dependency-name {
    font-weight: 600;
    color: #555;
    margin-bottom: 5px;
}

.dependency-bar-container {
    display: flex;
    align-items: center;
    gap: 10px;
}

.dependency-bar {
    background: linear-gradient(90deg, #667eea 0%, #764ba2 100%);
    height: 25px;
    border-radius: 12px;
    transition: width 0.5s ease;
}

.dependency-count {
    color: #888;
    font-size: 0.9em;
    white-space: nowrap;
}

/* MITRE Cards */
.mitre-grid {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(350px, 1fr));
    gap: 20px;
    margin-top: 20px;
}

.mitre-card {
    border-radius: 12px;
    padding: 25px;
    box-shadow: 0 4px 15px rgba(0,0,0,0.1);
    transition: transform 0.3s ease;
}

.mitre-card:hover {
    transform: translateY(-5px);
}

.mitre-critical { background: linear-gradient(135deg, #ee0979 0%, #ff6a00 100%); color: white; }
.mitre-high { background: linear-gradient(135deg, #f093fb 0%, #f5576c 100%); color: white; }
.mitre-medium { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; }

.mitre-id {
    font-size: 1.5em;
    font-weight: bold;
    margin-bottom: 10px;
}

.mitre-name {
    font-size: 1.2em;
    margin-bottom: 15px;
    font-weight: 600;
}

.mitre-description {
    opacity: 0.9;
    line-height: 1.6;
    margin-bottom: 15px;
}

.mitre-link {
    display: inline-block;
    color: white;
    text-decoration: underline;
    margin-top: 10px;
    font-weight: 600;
}

/* Anti-Cheat Cards */
.anticheat-card {
    border-radius: 12px;
    padding: 25px;
    margin-bottom: 20px;
    border-left: 5px solid;
}

.severity-extreme {
    background: #f8d7da;
    border-color: #ee0979;
}

.severity-high {
    background: #fff3cd;
    border-color: #f5576c;
}

.severity-medium {
    background: #d1ecf1;
    border-color: #667eea;
}

.severity-low {
    background: #d4edda;
    border-color: #11998e;
}

.anticheat-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    margin-bottom: 15px;
}

.anticheat-header h3 {
    color: #333;
    margin: 0;
}

.anticheat-type {
    color: #666;
    margin-bottom: 10px;
}

.anticheat-desc {
    color: #555;
    line-height: 1.6;
    margin-bottom: 15px;
}

.anticheat-components ul {
    margin-left: 20px;
}

.anticheat-components li {
    margin-bottom: 5px;
    color: #666;
}

/* Security Features */
.security-features {
    margin-bottom: 30px;
}

.feature-grid {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
    gap: 20px;
    margin-top: 20px;
}

.security-feature {
    border-radius: 12px;
    padding: 20px;
    border: 2px solid;
    transition: transform 0.3s ease;
}

.security-feature:hover {
    transform: scale(1.02);
}

.feature-enabled {
    background: #d4edda;
    border-color: #11998e;
}

.feature-disabled {
    background: #f8d7da;
    border-color: #ee0979;
}

.feature-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    margin-bottom: 10px;
}

.feature-header h4 {
    color: #333;
    font-size: 1.2em;
}

.feature-status {
    font-size: 0.75em;
    font-weight: bold;
    padding: 4px 8px;
    border-radius: 4px;
    background: rgba(0,0,0,0.1);
}

.feature-name {
    font-weight: 600;
    color: #555;
    margin-bottom: 8px;
}

.feature-desc {
    color: #666;
    font-size: 0.9em;
    line-height: 1.5;
}

/* Version Info */
.info-grid {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
    gap: 25px;
}

.info-section {
    background: #f8f9fa;
    padding: 20px;
    border-radius: 8px;
    border-left: 4px solid #667eea;
}

.info-section.full-width {
    grid-column: 1 / -1;
}

.info-section h3 {
    color: #667eea;
    margin-bottom: 15px;
    font-size: 1.2em;
}

.info-section p {
    margin-bottom: 10px;
    color: #555;
}

/* Utilities */
.monospace {
    font-family: 'Consolas', 'Monaco', monospace;
    background: #f0f0f0;
    padding: 2px 6px;
    border-radius: 4px;
    font-size: 0.9em;
}

.flags {
    font-size: 0.85em;
    color: #666;
}

.copy-btn, .copy-btn-small {
    background: #667eea;
    color: white;
    border: none;
    padding: 8px 15px;
    border-radius: 6px;
    cursor: pointer;
    font-size: 0.85em;
    transition: all 0.3s ease;
    margin-top: 10px;
}

.copy-btn-small {
    padding: 4px 10px;
    font-size: 0.75em;
    margin-top: 0;
    margin-left: 10px;
}

.copy-btn:hover, .copy-btn-small:hover {
    background: #764ba2;
    transform: translateY(-2px);
}

.small {
    font-size: 0.85em;
}

/* Back to Top Button */
.back-to-top {
    position: fixed;
    bottom: 30px;
    right: 30px;
    background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
    color: white;
    border: none;
    width: 50px;
    height: 50px;
    border-radius: 50%;
    cursor: pointer;
    box-shadow: 0 4px 15px rgba(0,0,0,0.3);
    font-size: 1.2em;
    transition: all 0.3s ease;
    z-index: 1000;
    display: none;
}

.back-to-top:hover {
    transform: translateY(-5px);
    box-shadow: 0 6px 20px rgba(0,0,0,0.4);
}

/* Footer */
.footer {
    background: white;
    border-radius: 12px;
    padding: 20px;
    margin-top: 30px;
    text-align: center;
    box-shadow: 0 4px 15px rgba(0,0,0,0.1);
    color: #666;
}

.footer strong {
    color: #667eea;
}

/* Responsive */
@media (max-width: 768px) {
    .summary-grid {
        grid-template-columns: 1fr;
    }

    .tabs {
        flex-direction: column;
    }

    .tab-btn {
        width: 100%;
    }

    .security-score-container {
        flex-direction: column;
    }

    .mitre-grid {
        grid-template-columns: 1fr;
    }

    .feature-grid {
        grid-template-columns: 1fr;
    }

    .info-grid {
        grid-template-columns: 1fr;
    }
}

@media print {
    body {
        background: white;
        padding: 0;
    }

    .tabs, .back-to-top {
        display: none !important;
    }

    .tab-content {
        display: block !important;
        break-inside: avoid;
        page-break-inside: avoid;
    }

    .card {
        break-inside: avoid;
    }
}
";
        }

        private static string GetJavaScript()
        {
            return @"
// Tab switching
function openTab(evt, tabName) {
    const tabContents = document.getElementsByClassName('tab-content');
    for (let i = 0; i < tabContents.length; i++) {
        tabContents[i].classList.remove('active');
    }

    const tabBtns = document.getElementsByClassName('tab-btn');
    for (let i = 0; i < tabBtns.length; i++) {
        tabBtns[i].classList.remove('active');
    }

    document.getElementById(tabName).classList.add('active');
    evt.currentTarget.classList.add('active');
}

// Copy to clipboard
function copyToClipboard(text) {
    navigator.clipboard.writeText(text).then(function() {
        alert('Copied to clipboard: ' + text.substring(0, 50) + '...');
    }, function(err) {
        alert('Failed to copy: ' + err);
    });
}

// Back to top button
window.onscroll = function() {
    const backToTop = document.getElementById('backToTop');
    if (document.body.scrollTop > 300 || document.documentElement.scrollTop > 300) {
        backToTop.style.display = 'block';
    } else {
        backToTop.style.display = 'none';
    }
};

function scrollToTop() {
    window.scrollTo({
        top: 0,
        behavior: 'smooth'
    });
}

// Add smooth scroll to all links
document.querySelectorAll('a[href^=""#""]').forEach(anchor => {
    anchor.addEventListener('click', function (e) {
        e.preventDefault();
        const target = document.querySelector(this.getAttribute('href'));
        if (target) {
            target.scrollIntoView({
                behavior: 'smooth'
            });
        }
    });
});

// Initialize
document.addEventListener('DOMContentLoaded', function() {
    console.log('CrxMem PE Analysis Report loaded successfully');

    // Animate cards on load
    const cards = document.querySelectorAll('.card');
    cards.forEach((card, index) => {
        setTimeout(() => {
            card.style.opacity = '1';
        }, index * 100);
    });
});
";
        }
    }
}
